import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import NextTopLoader from "nextjs-toploader";
import { NextIntlClientProvider, useMessages } from "next-intl";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Web3together",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.png",
      href: "/favicon.png",
      type: "image/x-icon",
    },
  },
};

export default function RootLayout({ children, params: { locale } }: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>) {
  const messages = useMessages()
  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}
        className={`${inter.className} !overflow-x-hidden`}>
        <div className="w-full md:w-10/12 mx-auto px-5 md:px-0">
          <NextTopLoader
            color="#F2A93B"
            showSpinner={false}
          />
          <NextIntlClientProvider messages={messages}>
            <Navbar />
          {children}
          </NextIntlClientProvider>
        </div>
      </body>
    </html>
  )
}